FROM python

WORKDIR /model_test

COPY / /model_test

RUN pip install tensorflow 

RUN pip install numpy 

RUN pip install keras 

RUN pip install matplotlib 

RUN pip install pillow 

RUN pip install opencv-python 

RUN pip install pandas 

CMD ["python", "code.py"]
