FROM python

WORKDIR /model_test

COPY / /model_test 

RUN pip install numpy  

RUN pip install matplotlib  

RUN pip install opencv-python

RUN pip install scipy

RUN pip install scikit-learn

RUN pip install seaborn

RUN pip install pandas 

CMD ["python", "code.py"]
